[package]
name = "boardgen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[lib]
name = "boardgen"
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = "0.2.92"
