on:
  push:
    branches:
      - 'main'
env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish site
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun i --frozen-lockfile
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Build
      run: bun run build
    - name: Publish
      run: bunx wrangler pages deploy --project-name=dominogod dist/
